name: Auto Tag on Push

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0 # important to fetch all tags and history

      - name: Set up date tag
        id: date
        run: echo "DATE_TAG=$(date -u +'%y.%m.%d')" >> "$GITHUB_OUTPUT"

      - name: Create and Push Tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Create date and latest tags
          git tag -f "${{ steps.date.outputs.DATE_TAG }}"
          git tag -f latest

          # Push both tags
          git push origin --force "${{ steps.date.outputs.DATE_TAG }}" latest

      - name: Create GitHub Release 🎉
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.DATE_TAG }}
          release_name: Release ${{ steps.date.outputs.DATE_TAG }}
