name: Auto Tag and Release on Push

on:
  push:
    branches:
      - master

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    # This single permissions block controls both push and release access
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          # Use the GITHUB_TOKEN instead of a PAT
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up date tag
        id: date
        run: echo "DATE_TAG=$(date -u +'%y.%m.%d')" >> "$GITHUB_OUTPUT"

      - name: Create and Push Tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git tag -f "${{ steps.date.outputs.DATE_TAG }}"
          git tag -f latest

          # The push now works without changing the remote URL
          git push origin --force "${{ steps.date.outputs.DATE_TAG }}" latest

      - name: Create GitHub Release 🎉
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.DATE_TAG }}
          release_name: Release ${{ steps.date.outputs.DATE_TAG }}
