name: Auto Tag on Push

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # important to fetch all tags and history

      - name: Set up date variables
        id: date
        run: |
          DATE_TAG=$(date -u +"%y.%m.%d")
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV

      - name: Create or move tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Tag with current date format (YY.MM.DD)
          git tag -f "$DATE_TAG"

          # Update 'latest' tag to this commit
          git tag -f latest
      - name: Set git remote with PAT
        run: git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
      - name: Push tags
        run: |
          git push origin "$DATE_TAG" --force
          git push origin latest --force
